=== sarazapata015/examen/src/examen.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name = "bib">
    <xs:complexType>
      <xs:sequence>
        <xs:element name = "libro"  maxOccurs="unbounded" minOccurs="0" >
          <xs:complexType>
            <xs:sequence>
              <xs:element type = "xs:string" name = "titulo"/>
              <xs:element name = "autor"  maxOccurs="unbounded" minOccurs="0" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="apellido" maxOccurs="unbounded" type="xs:string">
                      <xs:simpleType >
                        <xs:restriction base="xs:string">
                          <xs:pattern value="([a-z])+"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type = "xs:string" name = "nombre"/>
                    <xs:element type = "xs:int" name = "cedula"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="ciudad" />
                  <xs:attribute type="xs:string" name="pais" />
                  <xs:attribute type="xs:string" name="residencia"/>
                  <xs:attribute type="xs:string" name="telefono" />
                  <xs:attribute type="xs:string" name="correo" />
                  <xs:attribute type="xs:string" name="foto" />
                </xs:complexType>
              </xs:element>
              <xs:element type = "xs:string" name = "editorial"/>
              <xs:element type = "xs:float" name = "precio"/>
              <xs:element type = "xs:string" name = "codigo"/>
            </xs:sequence>
            <xs:attribute name="anyo" type="xs:unsignedInt" use="required" >
              <xs:simpleType >
                <xs:restriction base="xs:positiveInteger">
                  <xs:minInclusive value="1990"/>
                  <xs:maxInclusive value="2020"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sarazapata015/examen/src/examen.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type ="text/xsl" href="bib.xsl"?>
<!DOCTYPE bib>
<bib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="examen.xsd">
    <libro anyo="1994">
        <titulo>TCP/IP Illustrated</titulo>
        <autor foto="https://crearmiempresa.es/wp-content/uploads/2015/07/frases-de-steve-jobs.jpg" ciudad="Medellin" pais="Colombia" residencia="Enciso" telefono="2922619" correo="steven">
            <apellido>stevens</apellido>
            <nombre>W.</nombre>
            <cedula>589641</cedula>
        </autor>

        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
        <codigo>ESP</codigo>

    </libro>
    <libro anyo="1992">
        <titulo>Advanced Programming for Unix environment</titulo>
        <autor>
            <apellido>stevens</apellido>
            <nombre>W.</nombre>
            <cedula>654321</cedula>

        </autor>
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
        <codigo>ALE</codigo>
    </libro>
    <libro anyo="2000">
        <titulo>Data on the Web</titulo>
        <autor>
            <apellido>abiteboul</apellido>
            <nombre>Serge</nombre>
            <cedula>789456</cedula>

        </autor>
        <autor>
            <apellido>buneman</apellido>
            <nombre>Peter</nombre>
            <cedula>654178</cedula>
        </autor>
        <autor>
            <apellido>suciu</apellido>
            <nombre>Carlos</nombre>
            <cedula>963258</cedula>
        </autor>
        <editorial>Morgan Kaufmann editorials</editorial>
        <precio>39.95</precio>
        <codigo>FRA</codigo>
    </libro>
    <libro anyo="1999">
        <titulo> Economics of Technology for Digital TV</titulo>
        <autor>
            <apellido>gerbarg</apellido>
            <nombre>Darcy</nombre>
            <cedula>741258</cedula>
        </autor>
        <editorial>Kluwer Academic editorials</editorial>
        <precio>129.95</precio>
        <codigo>ITA</codigo>
    </libro>
</bib>
